<?php

namespace SForce\Wsdl;

class ExceptionCode
{
    const __default = 'APEX_REST_SERVICES_DISABLED';

    const APEX_REST_SERVICES_DISABLED = 'APEX_REST_SERVICES_DISABLED';

    const APEX_TRIGGER_COUPLING_LIMIT = 'APEX_TRIGGER_COUPLING_LIMIT';

    const API_CURRENTLY_DISABLED = 'API_CURRENTLY_DISABLED';

    const API_DISABLED_FOR_ORG = 'API_DISABLED_FOR_ORG';

    const ARGUMENT_OBJECT_PARSE_ERROR = 'ARGUMENT_OBJECT_PARSE_ERROR';

    const ASYNC_OPERATION_LOCATOR = 'ASYNC_OPERATION_LOCATOR';

    const ASYNC_QUERY_UNSUPPORTED_QUERY = 'ASYNC_QUERY_UNSUPPORTED_QUERY';

    const BATCH_PROCESSING_HALTED = 'BATCH_PROCESSING_HALTED';

    const BIG_OBJECT_UNSUPPORTED_OPERATION = 'BIG_OBJECT_UNSUPPORTED_OPERATION';

    const CANNOT_DELETE_ENTITY = 'CANNOT_DELETE_ENTITY';

    const CANNOT_DELETE_OWNER = 'CANNOT_DELETE_OWNER';

    const CANT_ADD_STANDADRD_PORTAL_USER_TO_TERRITORY = 'CANT_ADD_STANDADRD_PORTAL_USER_TO_TERRITORY';

    const CANT_ADD_STANDARD_PORTAL_USER_TO_TERRITORY = 'CANT_ADD_STANDARD_PORTAL_USER_TO_TERRITORY';

    const CATEGORY_NOT_FOUND = 'CATEGORY_NOT_FOUND';

    const CIRCULAR_OBJECT_GRAPH = 'CIRCULAR_OBJECT_GRAPH';

    const CLIENT_NOT_ACCESSIBLE_FOR_USER = 'CLIENT_NOT_ACCESSIBLE_FOR_USER';

    const CLIENT_REQUIRE_UPDATE_FOR_USER = 'CLIENT_REQUIRE_UPDATE_FOR_USER';

    const CONTENT_ALREADY_AN_ASSET_EXCEPTION = 'CONTENT_ALREADY_AN_ASSET_EXCEPTION';

    const CONTENT_CUSTOM_DOWNLOAD_EXCEPTION = 'CONTENT_CUSTOM_DOWNLOAD_EXCEPTION';

    const CONTENT_HUB_AUTHENTICATION_EXCEPTION = 'CONTENT_HUB_AUTHENTICATION_EXCEPTION';

    const CONTENT_HUB_FILE_DOWNLOAD_EXCEPTION = 'CONTENT_HUB_FILE_DOWNLOAD_EXCEPTION';

    const CONTENT_HUB_FILE_HAS_NO_URL_EXCEPTION = 'CONTENT_HUB_FILE_HAS_NO_URL_EXCEPTION';

    const CONTENT_HUB_FILE_NOT_FOUND_EXCEPTION = 'CONTENT_HUB_FILE_NOT_FOUND_EXCEPTION';

    const CONTENT_HUB_INVALID_OBJECT_TYPE_EXCEPTION = 'CONTENT_HUB_INVALID_OBJECT_TYPE_EXCEPTION';

    const CONTENT_HUB_INVALID_PAGE_NUMBER_EXCEPTION = 'CONTENT_HUB_INVALID_PAGE_NUMBER_EXCEPTION';

    const CONTENT_HUB_INVALID_PAYLOAD = 'CONTENT_HUB_INVALID_PAYLOAD';

    const CONTENT_HUB_INVALID_RENDITION_PAGE_NUMBER_EXCEPTION = 'CONTENT_HUB_INVALID_RENDITION_PAGE_NUMBER_EXCEPTION';

    const CONTENT_HUB_ITEM_TYPE_NOT_FOUND_EXCEPTION = 'CONTENT_HUB_ITEM_TYPE_NOT_FOUND_EXCEPTION';

    const CONTENT_HUB_OBJECT_NOT_FOUND_EXCEPTION = 'CONTENT_HUB_OBJECT_NOT_FOUND_EXCEPTION';

    const CONTENT_HUB_OPERATION_NOT_SUPPORTED_EXCEPTION = 'CONTENT_HUB_OPERATION_NOT_SUPPORTED_EXCEPTION';

    const CONTENT_HUB_SECURITY_EXCEPTION = 'CONTENT_HUB_SECURITY_EXCEPTION';

    const CONTENT_HUB_TIMEOUT_EXCEPTION = 'CONTENT_HUB_TIMEOUT_EXCEPTION';

    const CONTENT_HUB_UNEXPECTED_EXCEPTION = 'CONTENT_HUB_UNEXPECTED_EXCEPTION';

    const CONTENT_IMAGE_SCALING_INVALID_ARGUMENTS_EXCEPTION = 'CONTENT_IMAGE_SCALING_INVALID_ARGUMENTS_EXCEPTION';

    const CONTENT_IMAGE_SCALING_INVALID_IMAGE_EXCEPTION = 'CONTENT_IMAGE_SCALING_INVALID_IMAGE_EXCEPTION';

    const CONTENT_IMAGE_SCALING_MAX_RENDITIONS_EXCEPTION = 'CONTENT_IMAGE_SCALING_MAX_RENDITIONS_EXCEPTION';

    const CONTENT_IMAGE_SCALING_TIMEOUT_EXCEPTION = 'CONTENT_IMAGE_SCALING_TIMEOUT_EXCEPTION';

    const CONTENT_IMAGE_SCALING_UNKNOWN_EXCEPTION = 'CONTENT_IMAGE_SCALING_UNKNOWN_EXCEPTION';

    const CUSTOM_METADATA_LIMIT_EXCEEDED = 'CUSTOM_METADATA_LIMIT_EXCEEDED';

    const CUSTOM_SETTINGS_LIMIT_EXCEEDED = 'CUSTOM_SETTINGS_LIMIT_EXCEEDED';

    const DATACLOUD_API_CLIENT_EXCEPTION = 'DATACLOUD_API_CLIENT_EXCEPTION';

    const DATACLOUD_API_DISABLED_EXCEPTION = 'DATACLOUD_API_DISABLED_EXCEPTION';

    const DATACLOUD_API_INVALID_QUERY_EXCEPTION = 'DATACLOUD_API_INVALID_QUERY_EXCEPTION';

    const DATACLOUD_API_SERVER_BUSY_EXCEPTION = 'DATACLOUD_API_SERVER_BUSY_EXCEPTION';

    const DATACLOUD_API_SERVER_EXCEPTION = 'DATACLOUD_API_SERVER_EXCEPTION';

    const DATACLOUD_API_TIMEOUT_EXCEPTION = 'DATACLOUD_API_TIMEOUT_EXCEPTION';

    const DATACLOUD_API_UNAVAILABLE = 'DATACLOUD_API_UNAVAILABLE';

    const DATA_INTEGRATION_INPUT_ERROR = 'DATA_INTEGRATION_INPUT_ERROR';

    const DATA_INTEGRATION_NOT_FOUND = 'DATA_INTEGRATION_NOT_FOUND';

    const DATA_INTEGRATION_NO_ACCESS = 'DATA_INTEGRATION_NO_ACCESS';

    const DATA_INTEGRATION_PACKAGE_ERROR = 'DATA_INTEGRATION_PACKAGE_ERROR';

    const DATA_INTEGRATION_SERVER_ERROR = 'DATA_INTEGRATION_SERVER_ERROR';

    const DATA_INTEGRATION_VENDOR_SETUP_ERROR = 'DATA_INTEGRATION_VENDOR_SETUP_ERROR';

    const DUPLICATE_ARGUMENT_VALUE = 'DUPLICATE_ARGUMENT_VALUE';

    const DUPLICATE_VALUE = 'DUPLICATE_VALUE';

    const EMAIL_BATCH_SIZE_LIMIT_EXCEEDED = 'EMAIL_BATCH_SIZE_LIMIT_EXCEEDED';

    const EMAIL_TO_CASE_INVALID_ROUTING = 'EMAIL_TO_CASE_INVALID_ROUTING';

    const EMAIL_TO_CASE_LIMIT_EXCEEDED = 'EMAIL_TO_CASE_LIMIT_EXCEEDED';

    const EMAIL_TO_CASE_NOT_ENABLED = 'EMAIL_TO_CASE_NOT_ENABLED';

    const ENTITY_NOT_QUERYABLE = 'ENTITY_NOT_QUERYABLE';

    const ENVIRONMENT_HUB_MEMBERSHIP_CONFLICT = 'ENVIRONMENT_HUB_MEMBERSHIP_CONFLICT';

    const EXCEEDED_ID_LIMIT = 'EXCEEDED_ID_LIMIT';

    const EXCEEDED_LEAD_CONVERT_LIMIT = 'EXCEEDED_LEAD_CONVERT_LIMIT';

    const EXCEEDED_MAX_FILTER_ENTITIES = 'EXCEEDED_MAX_FILTER_ENTITIES';

    const EXCEEDED_MAX_SIZE_REQUEST = 'EXCEEDED_MAX_SIZE_REQUEST';

    const EXCEEDED_MAX_SOBJECTS = 'EXCEEDED_MAX_SOBJECTS';

    const EXCEEDED_MAX_TYPES_LIMIT = 'EXCEEDED_MAX_TYPES_LIMIT';

    const EXCEEDED_QUOTA = 'EXCEEDED_QUOTA';

    const EXTERNAL_OBJECT_AUTHENTICATION_EXCEPTION = 'EXTERNAL_OBJECT_AUTHENTICATION_EXCEPTION';

    const EXTERNAL_OBJECT_CONNECTION_EXCEPTION = 'EXTERNAL_OBJECT_CONNECTION_EXCEPTION';

    const EXTERNAL_OBJECT_EXCEPTION = 'EXTERNAL_OBJECT_EXCEPTION';

    const EXTERNAL_OBJECT_UNSUPPORTED_EXCEPTION = 'EXTERNAL_OBJECT_UNSUPPORTED_EXCEPTION';

    const FEDERATED_SEARCH_ERROR = 'FEDERATED_SEARCH_ERROR';

    const FEED_NOT_ENABLED_FOR_OBJECT = 'FEED_NOT_ENABLED_FOR_OBJECT';

    const FUNCTIONALITY_NOT_ENABLED = 'FUNCTIONALITY_NOT_ENABLED';

    const FUNCTIONALITY_TEMPORARILY_UNAVAILABLE = 'FUNCTIONALITY_TEMPORARILY_UNAVAILABLE';

    const ID_REQUIRED = 'ID_REQUIRED';

    const ILLEGAL_QUERY_PARAMETER_VALUE = 'ILLEGAL_QUERY_PARAMETER_VALUE';

    const INACTIVE_OWNER_OR_USER = 'INACTIVE_OWNER_OR_USER';

    const INACTIVE_PORTAL = 'INACTIVE_PORTAL';

    const INSERT_UPDATE_DELETE_NOT_ALLOWED_DURING_MAINTENANCE = 'INSERT_UPDATE_DELETE_NOT_ALLOWED_DURING_MAINTENANCE';

    const INSTALL_KEY_INVALID = 'INSTALL_KEY_INVALID';

    const INSTALL_KEY_REQUIRED = 'INSTALL_KEY_REQUIRED';

    const INSUFFICIENT_ACCESS = 'INSUFFICIENT_ACCESS';

    const INSUFFICIENT_ACCESS_APEX_METADATA_DEPLOY = 'INSUFFICIENT_ACCESS_APEX_METADATA_DEPLOY';

    const INTERNAL_CANVAS_ERROR = 'INTERNAL_CANVAS_ERROR';

    const INVALID_ASSIGNMENT_RULE = 'INVALID_ASSIGNMENT_RULE';

    const INVALID_AUTH_HEADER = 'INVALID_AUTH_HEADER';

    const INVALID_BATCH_REQUEST = 'INVALID_BATCH_REQUEST';

    const INVALID_BATCH_SIZE = 'INVALID_BATCH_SIZE';

    const INVALID_CLIENT = 'INVALID_CLIENT';

    const INVALID_CROSS_REFERENCE_KEY = 'INVALID_CROSS_REFERENCE_KEY';

    const INVALID_DATE_FORMAT = 'INVALID_DATE_FORMAT';

    const INVALID_FIELD = 'INVALID_FIELD';

    const INVALID_FILTER_LANGUAGE = 'INVALID_FILTER_LANGUAGE';

    const INVALID_FILTER_VALUE = 'INVALID_FILTER_VALUE';

    const INVALID_ID_FIELD = 'INVALID_ID_FIELD';

    const INVALID_INPUT_COMBINATION = 'INVALID_INPUT_COMBINATION';

    const INVALID_LOCALE_LANGUAGE = 'INVALID_LOCALE_LANGUAGE';

    const INVALID_LOCATOR = 'INVALID_LOCATOR';

    const INVALID_LOGIN = 'INVALID_LOGIN';

    const INVALID_MULTIPART_REQUEST = 'INVALID_MULTIPART_REQUEST';

    const INVALID_NEW_PASSWORD = 'INVALID_NEW_PASSWORD';

    const INVALID_OLD_PASSWORD = 'INVALID_OLD_PASSWORD';

    const INVALID_OPERATION = 'INVALID_OPERATION';

    const INVALID_OPERATION_WITH_EXPIRED_PASSWORD = 'INVALID_OPERATION_WITH_EXPIRED_PASSWORD';

    const INVALID_PACKAGE_VERSION = 'INVALID_PACKAGE_VERSION';

    const INVALID_PAGING_OPTION = 'INVALID_PAGING_OPTION';

    const INVALID_QUERY_FILTER_OPERATOR = 'INVALID_QUERY_FILTER_OPERATOR';

    const INVALID_QUERY_KEY = 'INVALID_QUERY_KEY';

    const INVALID_QUERY_LOCATOR = 'INVALID_QUERY_LOCATOR';

    const INVALID_QUERY_SCOPE = 'INVALID_QUERY_SCOPE';

    const INVALID_QUERY_VALUE = 'INVALID_QUERY_VALUE';

    const INVALID_REPLICATION_DATE = 'INVALID_REPLICATION_DATE';

    const INVALID_SEARCH = 'INVALID_SEARCH';

    const INVALID_SEARCH_SCOPE = 'INVALID_SEARCH_SCOPE';

    const INVALID_SESSION_ID = 'INVALID_SESSION_ID';

    const INVALID_SOAP_HEADER = 'INVALID_SOAP_HEADER';

    const INVALID_SORT_OPTION = 'INVALID_SORT_OPTION';

    const INVALID_SSO_GATEWAY_URL = 'INVALID_SSO_GATEWAY_URL';

    const INVALID_TYPE = 'INVALID_TYPE';

    const INVALID_TYPE_FOR_OPERATION = 'INVALID_TYPE_FOR_OPERATION';

    const JIGSAW_ACTION_DISABLED = 'JIGSAW_ACTION_DISABLED';

    const JIGSAW_IMPORT_LIMIT_EXCEEDED = 'JIGSAW_IMPORT_LIMIT_EXCEEDED';

    const JIGSAW_REQUEST_NOT_SUPPORTED = 'JIGSAW_REQUEST_NOT_SUPPORTED';

    const JSON_PARSER_ERROR = 'JSON_PARSER_ERROR';

    const KEY_HAS_BEEN_DESTROYED = 'KEY_HAS_BEEN_DESTROYED';

    const LICENSING_DATA_ERROR = 'LICENSING_DATA_ERROR';

    const LICENSING_UNKNOWN_ERROR = 'LICENSING_UNKNOWN_ERROR';

    const LIMIT_EXCEEDED = 'LIMIT_EXCEEDED';

    const LOGIN_CHALLENGE_ISSUED = 'LOGIN_CHALLENGE_ISSUED';

    const LOGIN_CHALLENGE_PENDING = 'LOGIN_CHALLENGE_PENDING';

    const LOGIN_DURING_RESTRICTED_DOMAIN = 'LOGIN_DURING_RESTRICTED_DOMAIN';

    const LOGIN_DURING_RESTRICTED_TIME = 'LOGIN_DURING_RESTRICTED_TIME';

    const LOGIN_MUST_USE_SECURITY_TOKEN = 'LOGIN_MUST_USE_SECURITY_TOKEN';

    const MALFORMED_ID = 'MALFORMED_ID';

    const MALFORMED_QUERY = 'MALFORMED_QUERY';

    const MALFORMED_SEARCH = 'MALFORMED_SEARCH';

    const MISMATCHING_VERSIONS = 'MISMATCHING_VERSIONS';

    const MISSING_ARGUMENT = 'MISSING_ARGUMENT';

    const MISSING_RECORD = 'MISSING_RECORD';

    const MODIFIED = 'MODIFIED';

    const MULTIPLE_RECORDS_FOUND = 'MULTIPLE_RECORDS_FOUND';

    const MUTUAL_AUTHENTICATION_FAILED = 'MUTUAL_AUTHENTICATION_FAILED';

    const NOT_ACCEPTABLE = 'NOT_ACCEPTABLE';

    const NOT_MODIFIED = 'NOT_MODIFIED';

    const NO_ACTIVE_DUPLICATE_RULE = 'NO_ACTIVE_DUPLICATE_RULE';

    const NO_RECIPIENTS = 'NO_RECIPIENTS';

    const NO_SOFTPHONE_LAYOUT = 'NO_SOFTPHONE_LAYOUT';

    const NUMBER_OUTSIDE_VALID_RANGE = 'NUMBER_OUTSIDE_VALID_RANGE';

    const OPERATION_TOO_LARGE = 'OPERATION_TOO_LARGE';

    const ORG_IN_MAINTENANCE = 'ORG_IN_MAINTENANCE';

    const ORG_IS_DOT_ORG = 'ORG_IS_DOT_ORG';

    const ORG_IS_SIGNING_UP = 'ORG_IS_SIGNING_UP';

    const ORG_LOCKED = 'ORG_LOCKED';

    const ORG_NOT_OWNED_BY_INSTANCE = 'ORG_NOT_OWNED_BY_INSTANCE';

    const PASSWORD_LOCKOUT = 'PASSWORD_LOCKOUT';

    const PORTAL_NO_ACCESS = 'PORTAL_NO_ACCESS';

    const POST_BODY_PARSE_ERROR = 'POST_BODY_PARSE_ERROR';

    const PRODUCT_NOT_FOUND = 'PRODUCT_NOT_FOUND';

    const QAT_HETEROGENOUS_CONTEXT_IDS = 'QAT_HETEROGENOUS_CONTEXT_IDS';

    const QAT_INVALID_CONTEXT_ID = 'QAT_INVALID_CONTEXT_ID';

    const QAT_INVALID_QUICK_ACTION = 'QAT_INVALID_QUICK_ACTION';

    const QUERY_TIMEOUT = 'QUERY_TIMEOUT';

    const QUERY_TOO_COMPLICATED = 'QUERY_TOO_COMPLICATED';

    const REALTIME_PROCESSING_TIME_EXCEEDED_LIMIT = 'REALTIME_PROCESSING_TIME_EXCEEDED_LIMIT';

    const RECORD_NOT_FOUND = 'RECORD_NOT_FOUND';

    const REQUEST_LIMIT_EXCEEDED = 'REQUEST_LIMIT_EXCEEDED';

    const REQUEST_RUNNING_TOO_LONG = 'REQUEST_RUNNING_TOO_LONG';

    const SERVER_UNAVAILABLE = 'SERVER_UNAVAILABLE';

    const SERVICE_DESK_NOT_ENABLED = 'SERVICE_DESK_NOT_ENABLED';

    const SOCIALCRM_FEEDSERVICE_API_CLIENT_EXCEPTION = 'SOCIALCRM_FEEDSERVICE_API_CLIENT_EXCEPTION';

    const SOCIALCRM_FEEDSERVICE_API_SERVER_EXCEPTION = 'SOCIALCRM_FEEDSERVICE_API_SERVER_EXCEPTION';

    const SOCIALCRM_FEEDSERVICE_API_UNAVAILABLE = 'SOCIALCRM_FEEDSERVICE_API_UNAVAILABLE';

    const SSO_SERVICE_DOWN = 'SSO_SERVICE_DOWN';

    const SST_ADMIN_FILE_DOWNLOAD_EXCEPTION = 'SST_ADMIN_FILE_DOWNLOAD_EXCEPTION';

    const STATE_TRANSITION_NOT_ALLOWED = 'STATE_TRANSITION_NOT_ALLOWED';

    const TOO_MANY_APEX_REQUESTS = 'TOO_MANY_APEX_REQUESTS';

    const TOO_MANY_JOBS = 'TOO_MANY_JOBS';

    const TOO_MANY_RECIPIENTS = 'TOO_MANY_RECIPIENTS';

    const TOO_MANY_RECORDS = 'TOO_MANY_RECORDS';

    const TRIAL_EXPIRED = 'TRIAL_EXPIRED';

    const TXN_SECURITY_APEX_ERROR = 'TXN_SECURITY_APEX_ERROR';

    const TXN_SECURITY_END_A_SESSION = 'TXN_SECURITY_END_A_SESSION';

    const TXN_SECURITY_FAIL_CLOSE = 'TXN_SECURITY_FAIL_CLOSE';

    const TXN_SECURITY_METERING_ERROR = 'TXN_SECURITY_METERING_ERROR';

    const TXN_SECURITY_NO_ACCESS = 'TXN_SECURITY_NO_ACCESS';

    const TXN_SECURITY_RUNTIME_ERROR = 'TXN_SECURITY_RUNTIME_ERROR';

    const TXN_SECURITY_TWO_FA_REQUIRED = 'TXN_SECURITY_TWO_FA_REQUIRED';

    const UNABLE_TO_LOCK_ROW = 'UNABLE_TO_LOCK_ROW';

    const UNKNOWN_ATTACHMENT_EXCEPTION = 'UNKNOWN_ATTACHMENT_EXCEPTION';

    const UNKNOWN_EXCEPTION = 'UNKNOWN_EXCEPTION';

    const UNKNOWN_ORG_SETTING = 'UNKNOWN_ORG_SETTING';

    const UNSUPPORTED_API_VERSION = 'UNSUPPORTED_API_VERSION';

    const UNSUPPORTED_ATTACHMENT_ENCODING = 'UNSUPPORTED_ATTACHMENT_ENCODING';

    const UNSUPPORTED_CLIENT = 'UNSUPPORTED_CLIENT';

    const UNSUPPORTED_MEDIA_TYPE = 'UNSUPPORTED_MEDIA_TYPE';

    const WEBSTORE_NOT_FOUND = 'WEBSTORE_NOT_FOUND';

    const XML_PARSER_ERROR = 'XML_PARSER_ERROR';
}
